/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.awt.Dialog.ModalityType;
import java.util.Objects;
import sistemadevacinas.Endereco;
import sistemadevacinas.Enfermeira;
import sistemadevacinas.Medico;
import sistemadevacinas.Pessoa;

/**
 *
 * @author Pedro Gaudio
 */
public class TelaLOgin extends javax.swing.JFrame {

    /**
     * Creates new form TelaLOgin
     */
    private Pessoa p1 = new Pessoa();
    private Medico m1 = new Medico();
    private Enfermeira e1 = new Enfermeira();

    public TelaLOgin() {
        initComponents();
        inicializacao();
    }

    private void inicializacao() {
        // paciente

        p1 = new Pessoa("pedro augusto", 29, 404882, "pedrogaudio@live.com", "pedro", "1234",
                new Endereco("Rua Teste", "XPTO", 12, "Bairro Teste", "Estado Teste", "Cidade Teste", "04052030"));

        // Medico-- além dos dados da pessoa, passo os exclusivos de medico
        m1 = new Medico("medico teste", 29, 404882, "pedrogaudio@live.com", "medico", "1234",
                new Endereco("Rua Teste", "XPTO", 12, "Bairro Teste", "Estado Teste", "Cidade Teste", "04052030"), 1234,
                "Procto", false);

        // Enfermeira-- além dos dados da pessoa, passo os exclusivos de enfermeira
        e1 = new Enfermeira("enfemeira teste", 29, 404882, "pedrogaudio@live.com", "enfermeira", "1234",
                new Endereco("Rua Teste", "XPTO", 12, "Bairro Teste", "Estado Teste", "Cidade Teste", "04052030"), 666);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtLogin = new javax.swing.JTextField();
        txtSenha = new javax.swing.JPasswordField();
        lblLogin = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();
        cbPerfil = new javax.swing.JComboBox<>();
        lblPerfil = new javax.swing.JLabel();
        btnAcessar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaActionPerformed(evt);
            }
        });

        lblLogin.setText("Login:");

        lblSenha.setText("Senha:");

        cbPerfil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Paciente", "Medico", "Enfermeira" }));

        lblPerfil.setText("Perfil:");

        btnAcessar.setText("Logar");
        btnAcessar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcessarActionPerformed(evt);
            }
        });

        jLabel1.setText("Tela de Login");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(btnAcessar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblLogin)
                            .addComponent(lblSenha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(txtLogin)
                            .addComponent(txtSenha)
                            .addComponent(cbPerfil, 0, 131, Short.MAX_VALUE))))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLogin))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSenha))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPerfil))
                .addGap(32, 32, 32)
                .addComponent(btnAcessar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jLabel1.getAccessibleContext().setAccessibleName("Tela de Login");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAcessarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcessarActionPerformed
        if (validaAcesso(txtLogin.getText(), new String(txtSenha.getPassword()), cbPerfil.getSelectedIndex(),
                p1, m1, e1)) {
            if (cbPerfil.getSelectedIndex() == 0)// paciente
            {
                // close();
                // abre a tela para marcação de vacinação
                AreaOperacional telaMarcaConsulta = new AreaOperacional(p1, cbPerfil.getSelectedIndex());
                telaMarcaConsulta.setVisible(true);
                dispose();
            } else if (cbPerfil.getSelectedIndex() == 1)// medico
            {
                AreaOperacional telaMarcaConsulta = new AreaOperacional(m1, cbPerfil.getSelectedIndex());
                telaMarcaConsulta.setVisible(true);
                //  frame.dispose();
            } else// enfermeira
            {
                AreaOperacional telaMarcaConsulta = new AreaOperacional(e1, cbPerfil.getSelectedIndex());
                telaMarcaConsulta.setVisible(true);
                // frame.dispose();
            }
        }
    }//GEN-LAST:event_btnAcessarActionPerformed

    private void txtSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLOgin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLOgin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLOgin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLOgin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLOgin().setVisible(true);
            }
        });
    }

    public boolean validaAcesso(String login, String senha, int perfil, Pessoa p1, Medico m1, Enfermeira e1) {

        // Pessoa p = new Pessoa();
        if (perfil == 0) {
            if (Objects.equals(login.toUpperCase(), p1.getLogin().toUpperCase())
                    && Objects.equals(senha.toUpperCase(), p1.getSenha().toUpperCase())) {
                return true;
            }
        } else if (perfil == 1) {
            if (Objects.equals(login.toUpperCase(), m1.getLogin().toUpperCase())
                    && Objects.equals(senha.toUpperCase(), m1.getSenha().toUpperCase())) {
                return true;
            }
        } else {
            if (Objects.equals(login.toUpperCase(), e1.getLogin().toUpperCase())
                    && Objects.equals(senha.toUpperCase(), e1.getSenha().toUpperCase())) {
                return true;
            }
        }

        return false;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcessar;
    private javax.swing.JComboBox<String> cbPerfil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblPerfil;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables
}
